name: Generate and Publish Documentation

on:
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: glu
          fetch-depth: 0

      - name: Run Gludoc to generate documentation
        uses: gesslar/gludoc@main
        with:
          source: './glu/library'
          destination: './generated-wiki'
          debug: 'false'

      - name: Checkout wiki repository
        uses: actions/checkout@v4
        with:
          repository: gesslar/glu.wiki
          ref: master
          path: wiki
          fetch-depth: 0
          token: ${{ secrets.WIKI_PAT }}

      - name: Copy generated docs to wiki
        run: |
          pwd
          # ls -R ./
          cd wiki && pwd && ls -R && find . -type f -name '*.md' ! -name 'Home.md' ! -name '_Footer.md' -exec git rm -f {} + && cd ..
          cp -Rv ./generated-wiki/* ./wiki/

      - name: Check for Pristine State
        id: check_pristine
        run: |
          # Check if there are uncommitted changes
          cd wiki
          if [[ -n $(git status --porcelain) ]]; then
            echo "pristine=👍🏻" >> $GITHUB_OUTPUT
          else
            echo "pristine=👎🏻" >> $GITHUB_OUTPUT
          fi

      - name: Publish to Wiki
        if: steps.check_pristine.outputs.pristine == '👍🏻'
        env:
          GITHUB_TOKEN: ${{ secrets.WIKI_PAT }}
        run: |
          cd wiki
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update wiki documentation from main repository"
          git push origin master
