name: Generate and Publish Documentation

on:
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: glu
          fetch-depth: 0

      - name: Run Gludoc to generate documentation
        uses: gesslar/gludoc@main
        with:
          source: './glu/library'
          destination: './generated-wiki'
          debug: 'false'

      - name: Checkout wiki repository
        uses: actions/checkout@v4
        with:
          repository: gesslar/glu.wiki
          ref: master
          path: wiki
          fetch-depth: 0
          token: ${{ secrets.WIKI_PAT }}

      - name: Copy generated docs to wiki
        run: |
          pwd
          ls -R ./
          find ./wiki/ -type f ! -name 'Home.md' ! -name '_Footer.md' -exec rm -v {} +
          cp -Rv ./generated-wiki/* ./wiki/

      - name: Publish to Wiki
        env:
          GITHUB_TOKEN: ${{ secrets.WIKI_PAT }}
        run: |
          cd wiki
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update wiki documentation from main repository"
          git push origin master
